### ISSUE TITLE
Circular import

### ISSUE THREAD

**Issue by xcvil** [huggingface/nanotron#191]
The circular import problem still exist from `nanotron 0.4` 

```shell
>>> from nanotron import logging
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/nanotron/logging.py", line 38, in <module>
    from nanotron.config.config import LoggingArgs
  File "/usr/local/lib/python3.10/dist-packages/nanotron/config/__init__.py", line 2, in <module>
    from nanotron.config.config import *
  File "/usr/local/lib/python3.10/dist-packages/nanotron/config/config.py", line 13, in <module>
    from nanotron.config.lighteval_config import LightEvalConfig
  File "/usr/local/lib/python3.10/dist-packages/nanotron/config/lighteval_config.py", line 5, in <module>
    from nanotron.config.parallelism_config import ParallelismArgs
  File "/usr/local/lib/python3.10/dist-packages/nanotron/config/parallelism_config.py", line 4, in <module>
    from nanotron.config.utils_config import (
  File "/usr/local/lib/python3.10/dist-packages/nanotron/config/utils_config.py", line 8, in <module>
    from nanotron.parallel.pipeline_parallel.engine import (
  File "/usr/local/lib/python3.10/dist-packages/nanotron/parallel/pipeline_parallel/__init__.py", line 1, in <module>
    from nanotron.parallel.pipeline_parallel.engine import PipelineEngine
  File "/usr/local/lib/python3.10/dist-packages/nanotron/parallel/pipeline_parallel/engine.py", line 8, in <module>
    from nanotron.logging import log_rank
ImportError: cannot import name 'log_rank' from partially initialized module 'nanotron.logging' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/nanotron/logging.py)
```

**Comment by zzhhjjj** [comment]
Hello. Have you used pip install nanotron? If so, could you please try running pip install -e . instead?

**Comment by Na00s** [comment]
I have the same exact problem when trying to runthe following .sh file
 accelerate launch --num_processes=1 -m \
    lighteval accelerate \
    --model_args="pretrained=Na0s/Llama-3.1-8B-Pruned-4-Layers_LoRA-PEFT-3.0" \
    --tasks "helm|commonsenseqa|0|0,original|mmlu|0|0,leaderboard|arc:challenge|0|0,helm|hellaswag|0|0,helm|piqa|0|0,helm|siqa|0|0,lighteval|triviaqa|0|0,helm|openbookqa|0|0,helm|boolq|0|0,helm|quac|0|0,leaderboard|gsm8k|0|0," \
    --output_dir="./evals/"
