### ISSUE TITLE
`RuntimeError: First class dim doesn't work with python 3.12` on minimal exmaple using 3.12 conda env

### ISSUE THREAD

**Issue by wilzh40** [huggingface/nanotron#217]
**Command run**
```CUDA_DEVICE_MAX_CONNECTIONS=1 torchrun --nproc_per_node=8 run_train.py --config-file examples/config_tiny_llama.yaml```

**Error message**
```
RuntimeError: First class dim doesn't work with python 3.12

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/weka/wilson/nanotron/run_train.py", line 15, in <module>
    from nanotron.config import DataArgs, DatasetStageArgs, NanosetDatasetsArgs, PretrainDatasetsArgs
  File "/mnt/weka/wilson/nanotron/src/nanotron/config/__init__.py", line 2, in <module>
    from nanotron.config.config import *
  File "/mnt/weka/wilson/nanotron/src/nanotron/config/config.py", line 13, in <module>
    from nanotron.config.lighteval_config import LightEvalConfig
  File "/mnt/weka/wilson/nanotron/src/nanotron/config/lighteval_config.py", line 5, in <module>
    from nanotron.config.parallelism_config import ParallelismArgs
  File "/mnt/weka/wilson/nanotron/src/nanotron/config/parallelism_config.py", line 4, in <module>
    from nanotron.config.utils_config import (
  File "/mnt/weka/wilson/nanotron/src/nanotron/config/utils_config.py", line 8, in <module>
    from nanotron.parallel.pipeline_parallel.engine import (
  File "/mnt/weka/wilson/nanotron/src/nanotron/parallel/pipeline_parallel/engine.py", line 9, in <module>
    from nanotron.optim.gradient_accumulator import GradientAccumulator
  File "/mnt/weka/wilson/nanotron/src/nanotron/optim/__init__.py", line 5, in <module>
    from nanotron.optim.zero import ZeroDistributedOptimizer
  File "/mnt/weka/wilson/nanotron/src/nanotron/optim/zero.py", line 9, in <module>
    from functorch.dim import tree_map
  File "/mnt/weka/wilson/miniconda3/envs/nanotron/lib/python3.12/site-packages/functorch/dim/__init__.py", line 5, in <module>
    import functorch._C
ImportError: initialization failed
```

Have we validated that this works on 3.12?

**Comment by wilzh40** [comment]
Thanks! Possible to modify the README that you only recommend `3.10`?
